/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing GroupPurchaseCategoryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GroupPurchaseCategoryApiTests : IDisposable
    {
        private GroupPurchaseCategoryApi instance;

        public GroupPurchaseCategoryApiTests()
        {
            instance = new GroupPurchaseCategoryApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupPurchaseCategoryApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GroupPurchaseCategoryApi
            //Assert.IsType<GroupPurchaseCategoryApi>(instance);
        }

        /// <summary>
        /// Test CreateGroupPurchaseCategory
        /// </summary>
        [Fact]
        public void CreateGroupPurchaseCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid groupUuid = null;
            //PurchaseCategoryCreate purchaseCategoryCreate = null;
            //var response = instance.CreateGroupPurchaseCategory(groupUuid, purchaseCategoryCreate);
            //Assert.IsType<PurchaseCategoryRead>(response);
        }

        /// <summary>
        /// Test DeleteGroupPurchaseCategory
        /// </summary>
        [Fact]
        public void DeleteGroupPurchaseCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid groupUuid = null;
            //Guid purchaseCategoryUuid = null;
            //var response = instance.DeleteGroupPurchaseCategory(groupUuid, purchaseCategoryUuid);
            //Assert.IsType<Message>(response);
        }

        /// <summary>
        /// Test GetGroupPurchaseCategories
        /// </summary>
        [Fact]
        public void GetGroupPurchaseCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid groupUuid = null;
            //int? page = null;
            //int? itemsPerPage = null;
            //var response = instance.GetGroupPurchaseCategories(groupUuid, page, itemsPerPage);
            //Assert.IsType<PaginatedListResponsePurchaseCategoryRead>(response);
        }

        /// <summary>
        /// Test UpdateGroupPurchaseCategory
        /// </summary>
        [Fact]
        public void UpdateGroupPurchaseCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid groupUuid = null;
            //Guid purchaseCategoryUuid = null;
            //PurchaseCategoryUpdate purchaseCategoryUpdate = null;
            //var response = instance.UpdateGroupPurchaseCategory(groupUuid, purchaseCategoryUuid, purchaseCategoryUpdate);
            //Assert.IsType<Message>(response);
        }
    }
}
