/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing GroupStatisticsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GroupStatisticsApiTests : IDisposable
    {
        private GroupStatisticsApi instance;

        public GroupStatisticsApiTests()
        {
            instance = new GroupStatisticsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupStatisticsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GroupStatisticsApi
            //Assert.IsType<GroupStatisticsApi>(instance);
        }

        /// <summary>
        /// Test GetGroupPurchaseCategoryStatistics
        /// </summary>
        [Fact]
        public void GetGroupPurchaseCategoryStatisticsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid groupUuid = null;
            //Currency? currency = null;
            //DateTime? before = null;
            //DateTime? after = null;
            //var response = instance.GetGroupPurchaseCategoryStatistics(groupUuid, currency, before, after);
            //Assert.IsType<PurchaseCategoryStatistics>(response);
        }
    }
}
