/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing GroupTransactionItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GroupTransactionItemsApiTests : IDisposable
    {
        private GroupTransactionItemsApi instance;

        public GroupTransactionItemsApiTests()
        {
            instance = new GroupTransactionItemsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupTransactionItemsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GroupTransactionItemsApi
            //Assert.IsType<GroupTransactionItemsApi>(instance);
        }

        /// <summary>
        /// Test GetGroupTransactionItems
        /// </summary>
        [Fact]
        public void GetGroupTransactionItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid groupUuid = null;
            //DateTime? before = null;
            //DateTime? after = null;
            //int? page = null;
            //int? itemsPerPage = null;
            //List<string>? tagNames = null;
            //Guid? purchaseCategoryUuid = null;
            //var response = instance.GetGroupTransactionItems(groupUuid, before, after, page, itemsPerPage, tagNames, purchaseCategoryUuid);
            //Assert.IsType<PaginatedListResponseTransactionItemReadWithTransactionData>(response);
        }
    }
}
