/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PaginatedListResponseUserRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginatedListResponseUserReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginatedListResponseUserRead
        //private PaginatedListResponseUserRead instance;

        public PaginatedListResponseUserReadTests()
        {
            // TODO uncomment below to create an instance of PaginatedListResponseUserRead
            //instance = new PaginatedListResponseUserRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginatedListResponseUserRead
        /// </summary>
        [Fact]
        public void PaginatedListResponseUserReadInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginatedListResponseUserRead
            //Assert.IsType<PaginatedListResponseUserRead>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'ItemsPerPage'
        /// </summary>
        [Fact]
        public void ItemsPerPageTest()
        {
            // TODO unit test for the property 'ItemsPerPage'
        }
    }
}
