/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseCategoryCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseCategoryCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseCategoryCreate
        //private PurchaseCategoryCreate instance;

        public PurchaseCategoryCreateTests()
        {
            // TODO uncomment below to create an instance of PurchaseCategoryCreate
            //instance = new PurchaseCategoryCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseCategoryCreate
        /// </summary>
        [Fact]
        public void PurchaseCategoryCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseCategoryCreate
            //Assert.IsType<PurchaseCategoryCreate>(instance);
        }

        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }

        /// <summary>
        /// Test the property 'CategoryDescription'
        /// </summary>
        [Fact]
        public void CategoryDescriptionTest()
        {
            // TODO unit test for the property 'CategoryDescription'
        }
    }
}
