/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseCategoryStatistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseCategoryStatisticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseCategoryStatistics
        //private PurchaseCategoryStatistics instance;

        public PurchaseCategoryStatisticsTests()
        {
            // TODO uncomment below to create an instance of PurchaseCategoryStatistics
            //instance = new PurchaseCategoryStatistics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseCategoryStatistics
        /// </summary>
        [Fact]
        public void PurchaseCategoryStatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseCategoryStatistics
            //Assert.IsType<PurchaseCategoryStatistics>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'ItemCount'
        /// </summary>
        [Fact]
        public void ItemCountTest()
        {
            // TODO unit test for the property 'ItemCount'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
