/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseCategoryStatisticsItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseCategoryStatisticsItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseCategoryStatisticsItem
        //private PurchaseCategoryStatisticsItem instance;

        public PurchaseCategoryStatisticsItemTests()
        {
            // TODO uncomment below to create an instance of PurchaseCategoryStatisticsItem
            //instance = new PurchaseCategoryStatisticsItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseCategoryStatisticsItem
        /// </summary>
        [Fact]
        public void PurchaseCategoryStatisticsItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseCategoryStatisticsItem
            //Assert.IsType<PurchaseCategoryStatisticsItem>(instance);
        }

        /// <summary>
        /// Test the property 'PurchaseCategory'
        /// </summary>
        [Fact]
        public void PurchaseCategoryTest()
        {
            // TODO unit test for the property 'PurchaseCategory'
        }

        /// <summary>
        /// Test the property 'ItemCount'
        /// </summary>
        [Fact]
        public void ItemCountTest()
        {
            // TODO unit test for the property 'ItemCount'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
