/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseCategoryRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseCategoryReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseCategoryRead
        //private PurchaseCategoryRead instance;

        public PurchaseCategoryReadTests()
        {
            // TODO uncomment below to create an instance of PurchaseCategoryRead
            //instance = new PurchaseCategoryRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseCategoryRead
        /// </summary>
        [Fact]
        public void PurchaseCategoryReadInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseCategoryRead
            //Assert.IsType<PurchaseCategoryRead>(instance);
        }

        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }

        /// <summary>
        /// Test the property 'CategoryDescription'
        /// </summary>
        [Fact]
        public void CategoryDescriptionTest()
        {
            // TODO unit test for the property 'CategoryDescription'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }
    }
}
