/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionUpdate
        //private TransactionUpdate instance;

        public TransactionUpdateTests()
        {
            // TODO uncomment below to create an instance of TransactionUpdate
            //instance = new TransactionUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionUpdate
        /// </summary>
        [Fact]
        public void TransactionUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionUpdate
            //Assert.IsType<TransactionUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'PurchaseCategoryUuid'
        /// </summary>
        [Fact]
        public void PurchaseCategoryUuidTest()
        {
            // TODO unit test for the property 'PurchaseCategoryUuid'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'TagNames'
        /// </summary>
        [Fact]
        public void TagNamesTest()
        {
            // TODO unit test for the property 'TagNames'
        }

        /// <summary>
        /// Test the property 'TransactionItems'
        /// </summary>
        [Fact]
        public void TransactionItemsTest()
        {
            // TODO unit test for the property 'TransactionItems'
        }
    }
}
