/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionItemRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionItemReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionItemRead
        //private TransactionItemRead instance;

        public TransactionItemReadTests()
        {
            // TODO uncomment below to create an instance of TransactionItemRead
            //instance = new TransactionItemRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionItemRead
        /// </summary>
        [Fact]
        public void TransactionItemReadInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionItemRead
            //Assert.IsType<TransactionItemRead>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'PurchaseCategoryUuid'
        /// </summary>
        [Fact]
        public void PurchaseCategoryUuidTest()
        {
            // TODO unit test for the property 'PurchaseCategoryUuid'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }

        /// <summary>
        /// Test the property 'CategoryDescription'
        /// </summary>
        [Fact]
        public void CategoryDescriptionTest()
        {
            // TODO unit test for the property 'CategoryDescription'
        }

        /// <summary>
        /// Test the property 'TagNames'
        /// </summary>
        [Fact]
        public void TagNamesTest()
        {
            // TODO unit test for the property 'TagNames'
        }
    }
}
