/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserTierUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserTierUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserTierUpdate
        //private UserTierUpdate instance;

        public UserTierUpdateTests()
        {
            // TODO uncomment below to create an instance of UserTierUpdate
            //instance = new UserTierUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserTierUpdate
        /// </summary>
        [Fact]
        public void UserTierUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserTierUpdate
            //Assert.IsType<UserTierUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'TierUuid'
        /// </summary>
        [Fact]
        public void TierUuidTest()
        {
            // TODO unit test for the property 'TierUuid'
        }
    }
}
