/*
 * Budgeting Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserRead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserReadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserRead
        //private UserRead instance;

        public UserReadTests()
        {
            // TODO uncomment below to create an instance of UserRead
            //instance = new UserRead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserRead
        /// </summary>
        [Fact]
        public void UserReadInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserRead
            //Assert.IsType<UserRead>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'TierUuid'
        /// </summary>
        [Fact]
        public void TierUuidTest()
        {
            // TODO unit test for the property 'TierUuid'
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'ProfileImageUrl'
        /// </summary>
        [Fact]
        public void ProfileImageUrlTest()
        {
            // TODO unit test for the property 'ProfileImageUrl'
        }
    }
}
